name: BUILD and DEPLOY to DOCKER HUB

on:
 push:
   branch: 
    -master

jobs:
 build-and-push:
  runs-on: ubuntu-latest
  steps:
  -name: Check Out Repo
   uses: actions/checkout@v2

  -name: Log in to Docker Hub
   uses: actions/login-action@v1
   with:
    username: ${{secret.DOCKER_USERNAME}}
    password: ${{secret.DOCKER_PASSWORD)}}

  -name: Build and Push Docker image
   uses: docker/build-push-action@v2
   with:
    context: .
    file: docker/Dockerfile.user
    push: true 
    tags: keshavvakul/wallet-nextjs:latest

  -name: Verify Pushed Image
   run: docker pull keshavvakul/wallet-nextjs:latest