name: BUILD and DEPLOY to DOCKER HUB

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Check Out Repo
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Fixed incorrect 'secret' syntax
          password: ${{ secrets.DOCKER_PASSWORD }} # Removed incorrect parenthesis

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: . # The build context, usually the root of your repo
          file: docker/Dockerfile.user # Path to your Dockerfile
          push: true # Ensures the image is pushed to Docker Hub
          tags: keshavvakul/wallet-nextjs:latest

      # Step 4: Verify the Pushed Image
      - name: Verify Pushed Image
        run: docker pull keshavvakul/wallet-nextjs:latest
